export default () => ({
    items: [
        {
            itemid: 'SECU24RW',
            title: 'PRS SE Custom 24 Sweetwater Exclusive - Natural Rosewood',
            status: 'in-stock',
            inventory: 400,
            thumb: 'https://media.sweetwater.com/images/items/750/SECU24RW-large.jpg',
            price: 200.95,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'LPTR18FHNH',
            title: 'Gibson Les Paul Tribute 2018 - Faded Honey Burst',
            status: 'in-stock',
            inventory: 100,
            thumb: 'https://media.sweetwater.com/images/items/750/LPTR18FHNH-large.jpg',
            price: 80.00,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'SGS18HCCH',
            title: 'Gibson SG Standard 2018 - Heritage Cherry',
            status: 'sold',
            stock: 0,
            thumb: 'https://media.sweetwater.com/images/items/750/SGS18HCCH-large.jpg',
            price: 200.50,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'TeleCPBjBl',
            title: 'Fender Classic Player Baja Telecaster - Blonde with Maple Fingerboard',
            status: 'in-stock',
            inventory: 5,
            thumb: 'https://media.sweetwater.com/images/items/750/TeleCPBjBl-large.jpg',
            price: '799.75',
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'LPS18HSCH',
            title: 'Gibson Les Paul Standard 2018 - Heritage Cherry Sunburst',
            status: 'in-stock',
            inventory: 2,
            thumb: 'https://media.sweetwater.com/images/items/750/LPS18HSCH-large.jpg',
            price: 3299.25,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'CE24BLACKOUT',
            title: 'PRS CE 24 Sweetwater Exclusive - Satin Blackout',
            status: 'in-stock',
            inventory: 1,
            thumb: 'https://media.sweetwater.com/images/items/750/CE24BLACKOUT-large.jpg',
            price: 1899.00,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'StratSBR3TSB',
            title: 'Fender Sandblasted Stratocaster, Sweetwater USA Exclusive',
            status: 'in-stock',
            inventory: 400,
            thumb: 'https://media.sweetwater.com/images/items/750/StratSBR3TSB-large.jpg',
            price: 1899.00,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'StratCV50SB',
            title: 'Squier Classic Vibe Stratocaster \'50s - 2-tone Sunburst',
            status: 'in-stock',
            inventory: 20,
            thumb: 'https://media.sweetwater.com/images/items/750/StratCV50SB-large.jpg',
            price: 399.00,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'PBassVMILPB',
            title: 'Squier Vintage Modified Precision Bass PJ',
            status: 'in-stock',
            inventory: 5,
            thumb: 'https://media.sweetwater.com/images/items/750/PBassVMILPB-large.jpg',
            price: 299.99,
            itemQty: 0,
            cartQty: 0,
        },
        {
            itemid: 'L4402RTTSdns',
            title: 'Lakland Skyline 44-02 Standard "Dent and Scratch"',
            status: 'in-stock',
            inventory: 4,
            thumb: 'https://media.sweetwater.com/images/items/750/L4402RTTSdns-large.jpg',
            price: 998.00,
            itemQty: 0,
            cartQty: 0,
        },
    ],

});
